security:
  oauth2:
    client:
      clientId: account-service
      client-secret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://gateway/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      database: ${MONGODB_DATABASE}
      uri: ${MONGODB_URI}

server:
  servlet:
    context-path: /accounts

feign:
  hystrix:
    enabled: true
