security:
  oauth2:
    client:
      clientId: statistics-service
      accessTokenUri: http://gateway/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      database: ${mongodb_database}
      uri: ${mongodb_uri}

server:
  servlet:
    context-path: /statistics
  port: 80

rates:
  url: https://api.exchangeratesapi.io
